[tox]
isolated_build = true
envlist =
    lint

[testenv:lint]
description = Run code linter and formatter checks (same as CI).
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files {posargs}

[testenv:format]
description = Auto-fix lint and format issues.
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure {posargs}
