name: Deploy Documentation

# Controls when the action will run. Triggers the workflow on push
on:
  workflow_dispatch:
  push:
    branches: [ main ]

    paths:
    - 'src/linkml_map/datamodel.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: uv sync

    - name: Generate and deploy docs
      run: |
        mkdir docs
        touch docs/.nojekyll
        make deploy-gh-doc
